openapi: 3.0.1
info:
  title: apiSample
  description: API Definition of apiSample
  version: 1.0.0
servers:
- url: http://localhost:8290/apisample
paths:
  /:
    get:
      responses:
        default:
          description: Default response
